### PR TITLE
fix: sdk async

### PR DESCRIPTION
**Pull request by Fraccaman**
## Describe your changes
Fix the sdk compiling with `async-send` feature flag. 
Added check on Makefile.

## Indicate on which release or other PRs this topic is based on
- 0.28.0

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Comment by Fraccaman** [comment]
spawn devnet help

**Comment by Fraccaman** [comment]
pls test devnet

**Comment by Fraccaman** [comment]
test devnet help

**Comment by Fraccaman** [comment]
test devnet help

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|date 2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-13T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-14T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-14T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-14T00:00:00Z|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|0.28.0|
|retention_period|2023-12-15T00:00:00Z|

**Comment by Chambers-ngl** [comment]
completed?

**Comment by jokerare000** [comment]
Db?

**Pull request closed without merging**
