### PR TITLE
Add a validator alias field to validator metadata

### LINKED ISSUE #2910: Unable to fetch validator alias because it's not part of validator metadata
As I have been following the development of a Namada explorer, I evidently saw the need to fetch the validator aliases, which it's not possible currently. It would be really needed for explorers, wallet interfaces, consensus dashboards, etc., so as to show full validator information (whether it's pre or post-genesis).

Thus, what I propose in order to address this problem is to add a new validator metadata field to store the validator alias. It would definitely improve the UX in the mentioned situations.

### PR DESCRIPTION
**Pull request by McDaan**
## Describe your changes

Closes #2910 

## Indicate on which release or other PRs this topic is based on
v0.34.0

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Comment by Fraccaman** [comment]
this looks nice! a couple of things are left to be done:

**Comment by McDaan** [comment]
> this looks nice! a couple of things are left to be done:
> 
> * regenerate the localnet files in `genesis/localnet`
> * re-run `make fmt`
> 
> Thanks for your contribution!

@Fraccaman Done!

**Comment by brentstone** [comment]
@McDaan Can you rebase this PR on the latest release v0.33? Alternatively, let me know if you'd be fine with me cleaning this up a bit myself.

**Comment by McDaan** [comment]
> @McDaan Can you rebase this PR on the latest release v0.33? Alternatively, let me know if you'd be fine with me cleaning this up a bit myself.

@brentstone I'm trying to figure out how to do it correctly, but I don't want to mess up anything - so, yes, I'd be fine if you do so instead in order to avoid conflicts. Thanks :)

**Comment by McDaan** [comment]
@brentstone Done. I just gave your write access just in case I've made any mistake.

**Review by tzemanovic — DISMISSED** [review]

**Pull request merged**
