### PR TITLE
Changing the inflation system documentation to be a bit more clear

### PR DESCRIPTION
**Pull request by mariari**
This pr is a minor change on the document file:

https://specs.namada.net/economics/inflation-system.html

I hope it makes the intent a bit more clear.

### CODE REVIEW

**Comment by mariari** [comment]
Should I also make a comment about what if `L_{SP_A}` is also 0. If no tokens are in the shielded pool, then the `I_{SP_A}` should also be 0, as there is nothing to give out, meaning the last_inflation should be 0. The same should be the same for staking

**Comment by cwgoes** [comment]
> Should I also make a comment about what if `L_{SP_A}` is also 0. If no tokens are in the shielded pool, then the `I_{SP_A}` should also be 0, as there is nothing to give out, meaning the last_inflation should be 0. The same should be the same for staking

Hmm, is this necessary? If there are no tokens in the shielded pool nothing can be claimed anyways. As the PD controller generally runs the reward rate might be high in that case, the rewards will just be unclaimed.

**Comment by mariari** [comment]
> > Should I also make a comment about what if `L_{SP_A}` is also 0. If no tokens are in the shielded pool, then the `I_{SP_A}` should also be 0, as there is nothing to give out, meaning the last_inflation should be 0. The same should be the same for staking
> 
> Hmm, is this necessary? If there are no tokens in the shielded pool nothing can be claimed anyways. As the PD controller generally runs the reward rate might be high in that case, the rewards will just be unclaimed.

I guess that is fine then, we can leave that part as is

**Review by brentstone — APPROVED** [review]
LGTM

**Pull request merged**
