### PR TITLE
Update crypto.md

### PR DESCRIPTION
**Pull request by tzemanovic**
moved from https://github.com/anoma/anoma/pull/1147

depends on https://github.com/anoma/namada/pull/266

Removed some TODOs/links to the closed issue https://github.com/anoma/anoma/issues/225, unsure if that still applies.

### CODE REVIEW

**Comment by tzemanovic** [comment]
@brentstone can you pls update this for https://github.com/anoma/namada/pull/278

**Comment by brentstone** [comment]
Do we want to update instances of "anoma" to "namada" in this PR?

**Comment by tzemanovic** [comment]
> Do we want to update instances of "anoma" to "namada" in this PR?

let me do that in #266 then we can rebase this PR

**Comment by tzemanovic** [comment]
I've done the renames in #266 and rebased this branch

**Pull request merged**
