### PR TITLE
Save conversion state into the state storage

### LINKED ISSUE #2189: Save conversion state in the block state storage
Currently, we save the MASP conversion state in the subspace every epoch. However, we don't need the old conversion state.
So, we can save the conversion state into the block state (RocksDB's `state` column family) not to record the diffs.
It would reduce the diffs size in the storage.

### PR DESCRIPTION
**Pull request by yito88**
## Describe your changes
closes #2189 

## Indicate on which release or other PRs this topic is based on
`0.26.0`

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Review by grarco — APPROVED** [review]
LGTM, thanks!

**Review by murisi — APPROVED** [review]
Looks good to me, thanks. A question: does the `invalid_transactions` test usually fail?

**Comment by grarco** [comment]
> Looks good to me, thanks. A question: does the `invalid_transactions` test usually fail?

I think it's failing because this PR doesn't include #2167, which is currently in draft

**Comment by yito88** [comment]
Thanks, `invalid_transactions` failed after this change. `run_ledger_ibc` failed due to #2167. Let me check `invalid_transactions`.

**Pull request merged**
