### PR TITLE
CLI revamp - 0.28.0

### PR DESCRIPTION
**Pull request by karbyshev**
This PR introduces a revamped structure of the wallet CLI suggested in #2135. The changes are based on v0.28.0.

The following changes were additionally introduced.

- For consistency, `--alias` argument is made obligatory for `gen` / `derive` commands.
- Raw (non-HD) key generation functionality is restored, hidden under `--raw` flag.
  Example: `namadaw gen --raw --alias key1`
- Fix alias string normalization
- Implemented `export` for MASP spending keys
- Implemented `import` for secret keys / MASP spending keys
- Implement `add` for secret keys
- Simplified interface of `add` command. Example: `namadaw add --alias my_entry --value val`. The supported values: 
  + secret key
  + public key
  + namada address
  + MASP spending key / viewing key / payment address
- Introduced bi-map for the alias-payment address book
- Implemented alias lookup by MASP payment key

Future work:

- implement ZIP32 functionality for spending key generation
- use `Alias` struct everywhere in order to force alias normalization?

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Review by cwgoes — CHANGES_REQUESTED** [review]
ACK modulo notes from testing:

- we should prevent generating two keys/addresses (including shielded & transparent) with the same alias
- `list` should show both shielded and transparent by default, unless filters are provided
- `list` should show both shielded keys and addresses, unless filters are provided
- `export` should support exporting shielded keys without passing `--shielded` (should only need the alias)
- `export` followed by `import` doesn't work - needs to be tested
- add function to remove keys
- test it more, recruit @bengtlofgren to help test

**Comment by karbyshev** [comment]
> ACK modulo notes from testing:
> 
> * we should prevent generating two keys/addresses (including shielded & transparent) with the same alias
> * `list` should show both shielded and transparent by default, unless filters are provided
> * `list` should show both shielded keys and addresses, unless filters are provided
> * `export` should support exporting shielded keys without passing `--shielded` (should only need the alias)
> * `export` followed by `import` doesn't work - needs to be tested
> * test `find` and make sure it isn't case-dependent, also make sure it doesn't require the password
> * add function to remove keys
> * test it more, recruit @bengtlofgren to help test

All are fixed.

**Comment by Fraccaman** [comment]
great work @karbyshev! Do you think this PR is ready?

**Comment by karbyshev** [comment]
@Fraccaman Thanks! I think it can be merged, but additional testing could be helpful.
ZIP32 keys are not implemented yet, and should be implemented in a separate PR, imho.

**Comment by karbyshev** [comment]
ZIP32 key derivation is implemented in #2417

**Pull request merged**
