### PR TITLE
0.32.0 rc

### PR DESCRIPTION
**Pull request by brentstone**
## Checklist before merging to `draft`
- [ ] I have added a changelog
- [ ] Git history is in acceptable state

### CODE REVIEW

**Comment by bengtlofgren** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-16T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Pull request closed without merging**
