### PR TITLE
MASP testnet revisions

### PR DESCRIPTION
**Pull request by cwgoes**
Changes in this branch:

- Altered epoch offsets in the conversion update function
- Added conversions query command (thanks @murisi)
- Updated CLI to add `--no-conversions` flag to print raw balances
- Minor CLI internal cleanup / code deduplication

### CODE REVIEW

**Comment by cwgoes** [comment]
pls spawn devnet [anoma-devnet-convert-2]

**Comment by cwgoes** [comment]
pls spawn devnet [anoma-devnet-convert-3]

**Comment by cwgoes** [comment]
pls spawn devnet [anoma-devnet-convert-4]

**Comment by cwgoes** [comment]
pls update wasm

**Comment by cwgoes** [comment]
pls update wasm

**Comment by cwgoes** [comment]
pls spawn devnet [anoma-devnet-convert-2]

**Comment by Fraccaman** [comment]
pls spawn devnet[anoma-devnet-convert,5,heliaxdev@ad825dcadb,OFF]

**Comment by Fraccaman** [comment]
pls spawn devnet[anoma-devnet-convert,5,heliaxdev@1be9883,OFF]

**Comment by Fraccaman** [comment]
pls spawn devnet[anoma-devnet-convert,5,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet[anoma-devnet-convert,5,heliaxdev@ad825dcadb,OFF]

**Pull request closed without merging**
