### PR TITLE
make ABCI++ the default and remove ABCI

### PR DESCRIPTION
**Pull request by tzemanovic**
based on #247

### CODE REVIEW

**Comment by juped** [comment]
We should base this on #222 which I am about to merge and include the relevant CI changes

**Comment by Fraccaman** [comment]
should we remove also the libp2p stuff here? or maybe another PR is better?

**Comment by tzemanovic** [comment]
> We should base this on #222 which I am about to merge and include the relevant CI changes

There's an outstanding issue with non-validator nodes (the result in non-deterministic in e2e tests, because non-validator nodes may or may not receive ABCI++ `ProcessProposal`). I'm just working on a fix, will rebase too

**Comment by tzemanovic** [comment]
pls update wasm

**Review by batconjurer — APPROVED** [review]

**Comment by Fraccaman** [comment]
pls update wasm

**Comment by tzemanovic** [comment]
pls update wasm

**Comment by tzemanovic** [comment]
pls publish wasm

**Comment by juped** [comment]
wasm is still a bit busted until #234 is done, btw

**Comment by Fraccaman** [comment]
@juped #234  looks good to me, can you check it on your side?

**Comment by juped** [comment]
looks good, need to factor out unrelated changes a bit

**Comment by tzemanovic** [comment]
launched a devnet [namada-devnet-0.5.4d591ed23da2](https://github.com/heliaxdev/anoma-network-config/releases/tag/namada-devnet-0.5.4d591ed23da2)

**Comment by tzemanovic** [comment]
> looks good, need to factor out unrelated changes a bit

thanks, will do

**Comment by tzemanovic** [comment]
later, we should also refactor the abcipp_shim and shim_types

**Pull request merged**
