### PR TITLE
Updated gas

### PR DESCRIPTION
**Pull request by grarco**
## Describe your changes

Updates genesis local files with the most update values for mainnet. Updates the `DEFAULT_GAS_LIMIT` in the sdk. Corrects tests.

## Checklist before merging 
- [ ] If this PR has some consensus breaking changes, I added the corresponding `breaking::` labels
    - This will require 2 reviewers to approve the changes
- [ ] If this PR requires changes to the docs or specs, a corresponding PR is opened in the `namada-docs` repo
    - Relevant PR if applies: 
- [ ] If this PR affects services such as `namada-indexer` or `namada-masp-indexer`, a corresponding PR is opened in that repo
    - Relevant PR if applies:

### CODE REVIEW

**Comment by brentstone** [comment]
So to summarize:
- hard-coded `DEFAULT_GAS_LIMIT = 50_000` from `250_000`
- `max_block_gas: 15_000_000 --> 3_000_000`
- `masp_fee_payment: 250_000 --> 50_000`
- `gas_scale: 10_000 --> 50_000`
- Cost per gas unit in NAM = `10^-5` as before (but changed in our testing config)

So now, the cost for a simple tx by default is 0.5 NAM.

@grarco Can you explain again why MASP fee payment and gas scale are changed?

**Comment by grarco** [comment]
Masp fee payment must be kept to a sensible value so that we are guaranteed that fee payment via the MASP happens in a reasonable amount of time. Gas scale was increased to reduce the gas used by transactions so that the fees could go down as well.

**Review by brentstone — APPROVED** [review]

**Comment by brentstone** [comment]
@grarco is this rdy for merge?

**Comment by grarco** [comment]
> @grarco is this rdy for merge?

Yes it is

**Pull request merged**
