### PR TITLE
Augment the functionality of `gen_localnet.py`

### PR DESCRIPTION
**Pull request by sug0**
## Describe your changes

This PR augments the functionality of `gen_localnet.py` with the ability to generate full node base directories. Moreover, adds a new `localnet-2` localnet starter kit with 2 validator nodes, and a script to start from this new localnet with either of the validator nodes or a full node.

## Checklist before merging 
- [ ] If this PR has some consensus breaking changes, I added the corresponding `breaking::` labels
    - This will require 2 reviewers to approve the changes

### CODE REVIEW

**Comment by tzemanovic** [comment]
I think we could use the `init-genesis-validator` and `sign-genesis-txs` to add arbitrary number of validators to `localnet` instead

**Comment by sug0** [comment]
that's what I did. I modified the existing `localnet` dir with those cmds

**Comment by tzemanovic** [comment]
> that's what I did. I modified the existing `localnet` dir with those cmds

ah I see. Can we do that so that the script makes it on-demand in a temp dir so we don't need to track `localnet-2`?

**Comment by sug0** [comment]
> > that's what I did. I modified the existing `localnet` dir with those cmds
> 
> ah I see. Can we do that so that the script makes it on-demand in a temp dir so we don't need to track `localnet-2`?

sure, should be doable

**Review by tzemanovic — APPROVED** [review]

**Pull request merged**
