### PR TITLE
Add TCP transport support for Ledger wallet

### PR DESCRIPTION
**Pull request by tzemanovic**
## Describe your changes

TODO:
- [x] add instructions on how to setup and use emulator

## Indicate on which release or other PRs this topic is based on

#3570

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Review by murisi — APPROVED** [review]
Looks good to me, thanks! Tested this on both the physical device and Speculos, and everything is working. It would have been nice to avoid needing to use macros, but it seems like the definition of `Exchange` precludes the use of trait objects.

**Comment by tzemanovic** [comment]
> Looks good to me, thanks! Tested this on both the physical device and Speculos, and everything is working. It would have been nice to avoid needing to use macros, but it seems like the definition of `Exchange` precludes the use of trait objects.

Agree, it would be nice to get rid of the macro. I think we could make an enum for the transport layer. I'll add the change

**Comment by tzemanovic** [comment]
@murisi added https://github.com/anoma/namada/commit/8f5cc8bd3b9d934c02469eb9029a85504f62085e

**Comment by tzemanovic** [comment]
squashed fixups in last push

**Review by murisi — APPROVED** [review]
Looks good, the device transport construction code is no longer duplicated. Thanks!

**Comment by tzemanovic** [comment]
@mergifyio requeue

**Pull request merged**
