### PR TITLE
relax bounds

### LINKED ISSUE #3467: Remove trait bounds from struct definitions where possible
In the native VPs we have bounds on `native_vp::Ctx` which also propagates to all the native VPs that wrap this up. We should only used the bounds on the impls

### PR DESCRIPTION
**Pull request by tzemanovic**
## Describe your changes

closes #3467

## Indicate on which release or other PRs this topic is based on

#3509 

- diff https://github.com/anoma/namada/pull/3577/files/f67da939cc9dee5a462f951378b56aac80d93a76..1ff2f61dca19320a3f16fd758e67ef84e214d279

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Comment by tzemanovic** [comment]
unfortunately the bound `S: StateRead` is still needed for native VP `Ctx` as the inner `PrefixIterators` needs it to get its `<S as StateRead>::DBIter::PrefixIter` which propagates up to all the native VPs

**Review by sug0 — APPROVED** [review]
nice, thanks!

**Comment by Fraccaman** [comment]
@mergify requeue

**Comment by Fraccaman** [comment]
@mergify requeue

**Pull request merged**
