### PR TITLE
Draft v0.17

### PR DESCRIPTION
**Pull request by tzemanovic**
WARNING: ☠️ do not merge this branch into your development branches and do not rely on it being stable. ☠️

contains:

- #1238 
- #1110
- #1431 
- #1432
- #1434 
- #1435 
- #1436
- #1443 
- #1449 
- #1456
- #1344
- #1444
- #1462 
- #1454
- #1469
- #1474 
- #892
- #1455

### CODE REVIEW

**Comment by adrianbrink** [comment]
Can we also add:

* https://github.com/anoma/namada/pull/1454
* https://github.com/anoma/namada/pull/1313

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.17,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.17,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls update wasm

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.17,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.17,3,heliaxdev@1be9883,ON]

**Pull request closed without merging**
