### PR TITLE
Fix namada encoding spec checks

### PR DESCRIPTION
**Pull request by sug0**
Should fix CI checks when building docs

### CODE REVIEW

**Comment by sug0** [comment]
pls update wasm

**Comment by sug0** [comment]
pls update wasm

**Comment by sug0** [comment]
pls update wasm

**Comment by sug0** [comment]
`make -C documentation/docs build` is still failing, but this time because `mdbook` is not found. we probably need a new PR to install the build deps, on the CI side

**Review by batconjurer — APPROVED** [review]

**Comment by sug0** [comment]
pls update wasm

**Review by james-chf — APPROVED** [review]

**Comment by james-chf** [comment]
> `make -C documentation/docs build` is still failing, but this time because `mdbook` is not found. we probably need a new PR to install the build deps, on the CI side

It's been removed recently in `main` - https://github.com/anoma/namada/commit/9ef7e84899a75edfcdfa677043965a9141bff75d

**Comment by sug0** [comment]
pls update wasm

**Pull request merged**
