### PR TITLE
draft: Validator eth secp keys

### PR DESCRIPTION
**Pull request by tzemanovic**
depends on #254 and #318

This PR adds 2 required validator eth bridge secp256k1 keys - hot and cold. Hot key will be used for signing validator set updates and cross-chain transactions (done by the ledger) and cold key for bridge governance (done on-demand by validators).

to-do:
- [x] add fn to derive Eth address from secp256k1 address (or use some crate)
- [x] Add a PoS storage map from eth address to namada address and set the associations when we write eth cold and hot keys
- [ ] update PoS VP to check eth keys
- [ ] update Pos VP test

### CODE REVIEW

**Comment by tzemanovic** [comment]
I think we can rebase this on https://github.com/anoma/namada/pull/379

**Comment by sug0** [comment]
note:
```rs
fn read_validator_eth_hot_key(
    &self,
    key: &Self::Address
) -> Option<Self::PublicKey>
```
this method should return `Option<ValidatorEthKey<Self::PublicKey>>` instead

**Comment by tzemanovic** [comment]
this is going to stay in draft for now - it's only partially finished, because some updates depend on other PoS changes that are not in eth-bridge-integration yet, but it unblocked the bridge dev itself

**Comment by cwgoes** [comment]
@batconjurer @tzemanovic Is this PR still relevant? Should it be merged into the Ethereum bridge integration branch, perhaps?

**Comment by sug0** [comment]
@cwgoes it's already in `eth-bridge-integration`, but not in `main`, due to missing some VPs, still

**Comment by adrianbrink** [comment]
Closing this since it's stale. If we need commits from this then @batconjurer @sug0 can pick them into a new PR.

**Pull request closed without merging**
