### PR TITLE
Ethereum bridge VP and e2e test clean up

### PR DESCRIPTION
**Pull request by tzemanovic**
moved from https://github.com/anoma/anoma/pull/1229

based on #250 

This is a PR to the mainline branch to clear up some code relating to the old Ethereum bridge design, which involved maintaining a queue of transfers. Also make the Ethereum bridge end-to-end test slightly clearer.

At the same time, trying to stop this test flaking in CI (https://github.com/anoma/namada/issues/161), though we probably shouldn't close the linked issue even after this PR lands for a while until we have not seen the flake. We need better logging to investigate why it is happening (I have seen it a few times).

### CODE REVIEW

**Comment by tzemanovic** [comment]
for some reason the eth e2e test failed with:

```
Reached a timeout for expect type of command
      Command: target/release/namadan --base-dir /tmp/.tmpISZg8d/e2e-test.434fc539cd4d48871ae5d/setup/validator-0/.anoma --mode validator ledger
      Logs: /tmp/.tmpISZg8d/e2e-test.434fc539cd4d48871ae5d/setup/validator-0/.anoma/logs/1660238793946600-namadan-9479372575242061887.log
       Needle: Tendermint node started
```

but in the log there's:

```
2022-08-11T17:26:34.024679Z  INFO namada_apps::node::ledger::tendermint_node: Tendermint node started
```

**Comment by tzemanovic** [comment]
pls update wasm

**Comment by tzemanovic** [comment]
@james-chf is this still relevant?

**Comment by james-chf** [comment]
The test does still need to be cleaned up but it's drifted a bit since this PR

I opened https://github.com/anoma/anoma/issues/1252 (on the old anoma repo by accident, will close that and make a new one on namada!)

I think this PR could be closed and we can fix it up in `eth-bridge-integration`

**Comment by james-chf** [comment]
Will fix this up in a new PR

**Pull request closed without merging**
