### PR TITLE
Update `eth-bridge-integration` with changes from `main`

### PR DESCRIPTION
**Pull request by james-chf**
For this PR, we should be able to get as much CI working as possible, with the exception of any ABCI tests. CI is only running for old ABCI right now so had to make some small changes so that things will still compile with the default feature flags (i.e. with the soon-to-be-removed ABCI) (see the commits made after the merge commit in this PR).

### CODE REVIEW

**Comment by james-chf** [comment]
pls update wasm

**Comment by juped** [comment]
main is not in a useful state to do this right now (soon, it should be in a better one)

**Comment by james-chf** [comment]
Yeah we will have to merge again soon once CI is working further.

**Comment by james-chf** [comment]
This PR is stale but I can cherry pick commits to make `eth-bridge-integration` compile with the default feature flags, then we can try merging latest `main` again

**Pull request closed without merging**
