### PR TITLE
docs for trunc_div functio

### PR DESCRIPTION
**Pull request by DoTheBestToGetTheBest**
- updated comment provides a detailed explanation of how trunc_div works

### CODE REVIEW

**Comment by DoTheBestToGetTheBest** [comment]
@Fraccaman hey is there a reason for closing this ?

**Comment by brentstone** [comment]
> @Fraccaman hey is there a reason for closing this ?

It was accidental. Thanks for the contribution, this will be merged soon after I clean it up a bit.

**Comment by DoTheBestToGetTheBest** [comment]
> > @Fraccaman hey is there a reason for closing this ?
> 
> It was accidental. Thanks for the contribution, this will be merged soon after I clean it up a bit.

thank you for your answer, i made another pr which was closed too( i don't know why too)

**Comment by brentstone** [comment]
@DoTheBestToGetTheBest Ah I see this is from a fork. Can you actually just remove the last commit and force-push back here with only your first commit? Your last commit does not obey our linting conventions. You can run `make clippy` within the namada repo to check the linting locally.

**Comment by DoTheBestToGetTheBest** [comment]
> h I see this is from a fork. Can you actually just remove the last commit and force-push back here with only your first commit? Your last commit does not obey our linting conventions.

so sorry not behind computer these days. I'm not in main branch and actual branch is not protected i guess you can do it if you have time ?

**Comment by brentstone** [comment]
> > > @Fraccaman hey is there a reason for closing this ?
> > 
> > 
> > It was accidental. Thanks for the contribution, this will be merged soon after I clean it up a bit.
> 
> thank you for your answer, i made another pr which was closed too( i don't know why too)

Feel free to let me know which one it is, but in general since announcing the airdrop we have received lots of spammy PRs that contribute very little and may appear to be attempts at airdrop farming, so we have been closing lots of them. We do want to merge legitimate attempts at contributing to the repo though.

**Comment by DoTheBestToGetTheBest** [comment]
> > > > @Fraccaman hey is there a reason for closing this ?
> > > 
> > > 
> > > It was accidental. Thanks for the contribution, this will be merged soon after I clean it up a bit.
> > 
> > 
> > thank you for your answer, i made another pr which was closed too( i don't know why too)
> 
> Feel free to let me know which one it is, but in general since announcing the airdrop we have received lots of spammy PRs that contribute very little and may appear to be attempts at airdrop farming, so we have been closing lots of them. We do want to merge legitimate attempts at contributing to the repo though.

it was this pr : https://github.com/anoma/namada/pull/2333

don't worry, i'm not looking to get the airdrop :)

i'm starting to learn about namada and trying to contribute on it while learning it :)

would be greats also to join a telegram or something where namada devs discuss :)

**Comment by brentstone** [comment]
> > > > > @Fraccaman hey is there a reason for closing this ?
> > > > 
> > > > 
> > > > It was accidental. Thanks for the contribution, this will be merged soon after I clean it up a bit.
> > > 
> > > 
> > > thank you for your answer, i made another pr which was closed too( i don't know why too)
> > 
> > 
> > Feel free to let me know which one it is, but in general since announcing the airdrop we have received lots of spammy PRs that contribute very little and may appear to be attempts at airdrop farming, so we have been closing lots of them. We do want to merge legitimate attempts at contributing to the repo though.
> 
> it was this pr : #2333
> 
> don't worry, i'm not looking to get the airdrop :)
> 
> i'm starting to learn about namada and trying to contribute on it while learning it :)
> 
> would be greats also to join a telegram or something where namada devs discuss :)

Awesome to hear! There is an active discord channel with several pages for devs and testnet usage. You should check them out and try using the latest testnets :). https://discord.com/invite/namada

**Comment by DoTheBestToGetTheBest** [comment]
> > > > > > @Fraccaman hey is there a reason for closing this ?
> > > > > 
> > > > > 
> > > > > It was accidental. Thanks for the contribution, this will be merged soon after I clean it up a bit.
> > > > 
> > > > 
> > > > thank you for your answer, i made another pr which was closed too( i don't know why too)
> > > 
> > > 
> > > Feel free to let me know which one it is, but in general since announcing the airdrop we have received lots of spammy PRs that contribute very little and may appear to be attempts at airdrop farming, so we have been closing lots of them. We do want to merge legitimate attempts at contributing to the repo though.
> > 
> > 
> > it was this pr : #2333
> > don't worry, i'm not looking to get the airdrop :)
> > i'm starting to learn about namada and trying to contribute on it while learning it :)
> > would be greats also to join a telegram or something where namada devs discuss :)
> 
> Awesome to hear! There is an active discord channel with several pages for devs and testnet usage. You should check them out and try using the latest testnets :). https://discord.com/invite/namada

also what do you suggest for me documentation to know like everything about anoma please? how the chain works, transactions type here, consesus, etc etc

**Comment by brentstone** [comment]
> > > > > > > @Fraccaman hey is there a reason for closing this ?
> > > > > > 
> > > > > > 
> > > > > > It was accidental. Thanks for the contribution, this will be merged soon after I clean it up a bit.
> > > > > 
> > > > > 
> > > > > thank you for your answer, i made another pr which was closed too( i don't know why too)
> > > > 
> > > > 
> > > > Feel free to let me know which one it is, but in general since announcing the airdrop we have received lots of spammy PRs that contribute very little and may appear to be attempts at airdrop farming, so we have been closing lots of them. We do want to merge legitimate attempts at contributing to the repo though.
> > > 
> > > 
> > > it was this pr : #2333
> > > don't worry, i'm not looking to get the airdrop :)
> > > i'm starting to learn about namada and trying to contribute on it while learning it :)
> > > would be greats also to join a telegram or something where namada devs discuss :)
> > 
> > 
> > Awesome to hear! There is an active discord channel with several pages for devs and testnet usage. You should check them out and try using the latest testnets :). https://discord.com/invite/namada
> 
> also what do you suggest for me documentation to know like everything about anoma please? how the chain works, transactions type here, consesus, etc etc

You will first want to read about the Namada blockchain, which is the first project in the anoma ecosystem and is the repo to which you contributed:
Website: https://namada.net/
Namada docs: https://docs.namada.net/
Namada specs: https://specs.namada.net/

Anoma itself is a more long-term project that we are also working on. Some resources are:
Website: https://anoma.net/
Anoma research: https://research.anoma.net/
At some point in the near future, the specs for anoma ([specs.anoma.net](https://specs.anoma.net/)) will be back online.

**Comment by DoTheBestToGetTheBest** [comment]
> > > > > > > > @Fraccaman hey is there a reason for closing this ?
> > > > > > > 
> > > > > > > 
> > > > > > > It was accidental. Thanks for the contribution, this will be merged soon after I clean it up a bit.
> > > > > > 
> > > > > > 
> > > > > > thank you for your answer, i made another pr which was closed too( i don't know why too)
> > > > > 
> > > > > 
> > > > > Feel free to let me know which one it is, but in general since announcing the airdrop we have received lots of spammy PRs that contribute very little and may appear to be attempts at airdrop farming, so we have been closing lots of them. We do want to merge legitimate attempts at contributing to the repo though.
> > > > 
> > > > 
> > > > it was this pr : #2333
> > > > don't worry, i'm not looking to get the airdrop :)
> > > > i'm starting to learn about namada and trying to contribute on it while learning it :)
> > > > would be greats also to join a telegram or something where namada devs discuss :)
> > > 
> > > 
> > > Awesome to hear! There is an active discord channel with several pages for devs and testnet usage. You should check them out and try using the latest testnets :). https://discord.com/invite/namada
> > 
> > 
> > also what do you suggest for me documentation to know like everything about anoma please? how the chain works, transactions type here, consesus, etc etc
> 
> You will first want to read about the Namada blockchain, which is the first project in the anoma ecosystem and is the repo to which you contributed: Website: https://namada.net/ Namada docs: https://docs.namada.net/ Namada specs: https://specs.namada.net/
> 
> Anoma itself is a more long-term project that we are also working on. Some resources are: Website: https://anoma.net/ Anoma research: https://research.anoma.net/ At some point in the near future, the specs for anoma ([specs.anoma.net](https://specs.anoma.net/)) will be back online.

Thank you so so much ! Really appreciate. Ty!

**Review by brentstone — APPROVED** [review]
LGTM

**Pull request merged**
