### PR TITLE
Test NAM reward unshields in `values_spanning_multiple_masp_digits`

### PR DESCRIPTION
**Pull request by sug0**
## Describe your changes

- Increase masp fee payment gas limit to `65000`
- Test NAM reward unshields in `values_spanning_multiple_masp_digits`.

## Checklist before merging 
- [ ] If this PR has some consensus breaking changes, I added the corresponding `breaking::` labels
    - This will require 2 reviewers to approve the changes
- [ ] If this PR requires changes to the docs or specs, a corresponding PR is opened in the `namada-docs` repo
    - Relevant PR if applies: 
- [ ] If this PR affects services such as `namada-indexer` or `namada-masp-indexer`, a corresponding PR is opened in that repo
    - Relevant PR if applies:

### CODE REVIEW

**Comment by grarco** [comment]
@sug0 with the increased gas for masp fee payment I believe this could close #3961

**Review by grarco — APPROVED** [review]

**Comment by sug0** [comment]
@Fraccaman ci is doing weird things here 😳

**Comment by Fraccaman** [comment]
what is happening?

**Comment by sug0** [comment]
`test-integration` is timing out in a weird way. it fails, but but every step in the job succeeds

**Comment by Fraccaman** [comment]
just re-run it, no idea why it happen sometimes

**Comment by grarco** [comment]
> just re-run it, no idea why it happen sometimes

Reran it 3 times, still no luck

**Pull request merged**
