### PR TITLE
Shared sdk integration Branch

### PR DESCRIPTION
**Pull request by mariari**
Integration branch for #921

### CODE REVIEW

**Comment by murisi** [comment]
pls update wasm

**Comment by murisi** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls spawn devnet [anoma-devnet-0.13.0-zondax,10,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [anoma-devnet-0.12.0,10,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [anoma-devnet-0.12.0,10,heliaxdev@1be9883,ON]

**Comment by cwgoes** [comment]
Is this still relevant?

**Comment by tzemanovic** [comment]
closing in favor of #1350

**Pull request closed without merging**
