### PR TITLE
e2e: wait for first block

### PR DESCRIPTION
**Pull request by Fraccaman**
## Describe your changes
Wait for first block before sending txs / querying rpc in e2e test.

## Indicate on which release or other PRs this topic is based on

0.31.6

## Checklist before merging to `draft`
- ~~[ ] I have added a changelog~~ tests only
- [x] Git history is in acceptable state

### CODE REVIEW

**Review by sug0 — APPROVED** [review]
Looks fine, but there's one e2e test failing. Is it just being flaky?

**Comment by brentstone** [comment]
Is this still useful?

**Comment by Fraccaman** [comment]
to me it is, @tzemanovic what do u think?

**Comment by tzemanovic** [comment]
> > to me it is, @tzemanovic what do u think?
> 
> I think the there are 3 e2e tests left that are often flaky in 0.33:
> 
>     * `double_signing_gets_slashed`
> 
>     * `pos_init_validator`
> 
>     * `proposal_ibc_token_inflation`
> 
> 
> I tried to fix the first one with no luck - the evidence reporting is handled by comet and it often times out (increasing the timeout doesn't seem to help). I don't think this change is going to affect this one, but it might help with others.
> 
> Let's rebase it and see if it helps with the other 2 with couple repeated runs.

Actually, there's no change for `proposal_ibc_token_inflation` and `pos_init_validator` was fixed in https://github.com/anoma/namada/pull/3023 so I think we can close this

**Pull request closed without merging**
