### PR TITLE
Murisi/masp testnet revisions merge fixes

### PR DESCRIPTION
**Pull request by murisi**
Fixing failing MASP E2E tests. More specifically made the following changes:
* Lengthened the epoch duration for the masp_txs_and_queries test
* Added missing RPC endpoints: results (to obtain accepted txs) and conv (to obtain conversions)
* Improved the error message produced when user overspends (from a stacktrace)

### CODE REVIEW

**Comment by cwgoes** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls spawn devnet[anoma-devnet-base,3,heliaxdev@ad825dcadb,OFF]

**Comment by Fraccaman** [comment]
pls spawn devnet[anoma-devnet-base,3,heliaxdev@ad825dcadb,OFF]

**Comment by Fraccaman** [comment]
pls spawn devnet[anoma-devnet-base,3,heliaxdev@ad825dcadb,OFF]

**Comment by Fraccaman** [comment]
pls load test [namada-467ae30.31f3753e7ff54b8,config_two.yaml,1;2;3;4;5;6]

**Comment by Fraccaman** [comment]
pls spawn devnet[anoma-devnet-0.9.0,3,heliaxdev@ad825dcadb,OFF]

**Comment by Fraccaman** [comment]
pls spawn devnet[anoma-devnet-0.9.0-masp,3,heliaxdev@ad825dcadb,OFF]

**Comment by cwgoes** [comment]
pls update wasm

**Pull request closed without merging**
