### PR TITLE
Add `ZeroizeOnDrop` to ed25519 keys

### PR DESCRIPTION
**Pull request by sug0**
## Describe your changes

- Tag `ed25519` keys with `ZeroizeOnDrop`, to indicate their bytes are cleared uppon the key being dropped.
- ~~Switch to `k256` for `secp256k1` keys. It natively implements `Zeroize`~~ - done in base #1958

## Indicate on which release or other PRs this topic is based on

#1958 (first commit here 609e70d62ce56842633b85aab5958d0324122416)

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Comment by brentstone** [comment]
DId these keys not already have this behavior? See the tests `types::key::more_tests::zeroize_keypair_ed25519` and `types::key::more_tests_zeroize_keypair_secp256k1`?

**Comment by sug0** [comment]
oh @brentstone you're right. I didn't realize we were using a fork of libsecp that cleared these keys on drop. to be honest though, we should switch back to the upstream version of the crate. we can clear the sk in a way similar to what has been implemented in this pr (albeit it involves unsafe code). lmk what you think

**Comment by brentstone** [comment]
@sug0 yeah you're prob right that we should avoid using the fork if we can accomplish the same thing with your method. I defer to your judgment.

**Comment by tzemanovic** [comment]
looking back at this I think we should switch to use https://crates.io/crates/k256

**Pull request merged**
