### PR TITLE
faucet PoW

### LINKED ISSUE #959: Implement PoW based faucet
- generate public key
- brute-force a nonce
- hash nonce and public key until you have something with a couple of leading zeros
- faucet tx takes pk + nonce - faucet vp verifies that pow is valid
- faucet vp stores a mapping from pk to [nonces] - enforces that every pk can only ever submit a PoW puzzle once

### PR DESCRIPTION
**Pull request by tzemanovic**
closes #959

depends on #926 for storage keys macro, #966 for avoiding lifetime issues and #962 for tx fees

first commit from this PR: [f7b6378](https://github.com/anoma/namada/pull/961/commits/f7b63784490d0b119fa63f7d52c53441bbcec031)

This is a breaking change for client - to be able to withdraw from token, client must request PoW challenge from the faucet, solve it and submit `tx_testnet_faucet_transfer.wasm` tx instead of `tx_transfer.wasm`.

This is non-breaking change for genesis as the added `faucet_pow_difficulty` is optional (defaults to `0` - no challenge).

TODOs:
- [x] integrate in vp_faucet
- [x] initialize faucet account with difficulty if used in `init_chain.rs`
- [x] set `faucet_pow_difficulty` from genesis
- [x] add a `tx_faucet_transfer` wasm to send `token::Transfer` wrapped in `faucet::Solution` and increment counter
- [x] add RPC endpoint to obtain faucet challenge for a `token::Transfer`
- [x] integrate in the client transfer command (detect faucet source)
- [x] allow to configure faucet withdrawal limit from genesis
- [ ] add the PoW into the wrapper tx (with conditional compilation when `not(mainnet)` to allow fee-less tx (with minimum tx fees from #962)

### CODE REVIEW

**Comment by tzemanovic** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls spawn devnet [anoma-devnet-0.11.0,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [anoma-devnet-0.11.0,3,heliaxdev@1be9883,ON]

**Comment by tzemanovic** [comment]
there's a failing test in vp_faucet which needs updated

**Comment by tzemanovic** [comment]
> there's a failing test in vp_testnet_faucet which needs updated

fixed in the last commit

**Comment by tzemanovic** [comment]
pls update wasm

**Comment by tzemanovic** [comment]
closing in favor of #969

**Pull request closed without merging**
