### PR TITLE
namada/vm: disable floats in wasm

### LINKED ISSUE #1872: disable floats in wasm
The `floats` WasmFeature was temporarily enabled to workaround https://github.com/cosmos/ibc-rs/issues/850. Once this is resolved, we should disable it again.

_Originally posted by @tzemanovic in https://github.com/anoma/namada/pull/1327#discussion_r1314707105_

### PR DESCRIPTION
**Pull request by tzemanovic**
## Describe your changes

closes #1872

## Indicate on which release or other PRs this topic is based on

0.35.1

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Comment by Fraccaman** [comment]
can we move ibc back to wasm now?

**Comment by tzemanovic** [comment]
> can we move ibc back to wasm now?

@Fraccaman I'm not sure, it was an issue with M1/M2 which might still be there (https://github.com/anoma/namada/issues/1831)

**Comment by Fraccaman** [comment]
@yito88 do u know if we can compile ibc-rs to wasm now?

**Comment by yito88** [comment]
@Fraccaman I tried it in #2480 and it worked. I'm not sure whether the latest one works or not. I'll try it with 0.35.1

**Comment by yito88** [comment]
tx_ibc.wasm moved back to wasm worked in #3275

**Pull request merged**
