### PR TITLE
Get migration working

### PR DESCRIPTION
**Pull request by brentstone**
## Describe your changes
Upgrade the migration and test it interactively using an e2e test environment.

Plan: ship the `migration.json` file to everyone for them to migrate state. Provide explicit state migration instructions.

## Indicate on which release or other PRs this topic is based on
Based on #2835.

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-14T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-16T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-16T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-19T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by Fraccaman** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-19T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|3|
|faucet|on|
|indexer|off|

**Comment by brentstone** [comment]
|Field|Value|
|----|----|
|command|spawn devnet|
|template_name|it-se|
|retention_period|2024-03-21T23:00:00Z|
|epochs_per_year|131400|
|block_time|5|
|total_validators|2|
|faucet|on|
|indexer|off|

**Pull request merged**
