### PR TITLE
Fix up CI on `eth-bridge-integration`

### PR DESCRIPTION
**Pull request by james-chf**
Quick PR to fix up CI on `eth-bridge-integration`
- run `make fmt`
- update wasms

### CODE REVIEW

**Comment by james-chf** [comment]
pls update wasm

**Comment by sug0** [comment]
@james-chf seems like e2e tests are also broken here. I was looking into fixing them yesterday, but got nowhere 😬

**Comment by james-chf** [comment]
> should we try to fix them in this PR as well?

I'd say not in this PR, we can merge these easy fixes but the e2e test fixing will be more involved (should probably open issues for them)

**Comment by james-chf** [comment]
If the changes from this PR are in https://github.com/anoma/namada/pull/286 , then when that merges this PR can be closed

**Pull request closed without merging**
