### PR TITLE
Remove unstable feature from integration tests

### PR DESCRIPTION
**Pull request by batconjurer**
## Describe your changes

This refactors the integrations tests using generic I/O. This allows use to remove the unstable feature gate.

## Indicate on which release or other PRs this topic is based on
Depends on #1746

### CODE REVIEW

**Review by tzemanovic — DISMISSED** [review]
nice! (I tried this together with #1768)

**Comment by tzemanovic** [comment]
we could remove nightly from tests builds now - even though it's not 100% necessary it would help with reusing build artifacts with stable build

**Comment by batconjurer** [comment]
> we could remove nightly from tests builds now - even though it's not 100% necessary it would help with reusing build artifacts with stable build

We still have the unstable option `report-time` though right?

**Comment by tzemanovic** [comment]
> > we could remove nightly from tests builds now - even though it's not 100% necessary it would help with reusing build artifacts with stable build
> 
> We still have the unstable option `report-time` though right?

ah, you're right, nvm then

**Review by tzemanovic — APPROVED** [review]

**Pull request merged**
