### PR TITLE
Start using Tendermint v0.37.0-rc1 and compatible Rust crates

### PR DESCRIPTION
**Pull request by james-chf**
Relates to https://github.com/anoma/namada/issues/825

This PR:
- updates `tendermint-rs`/`ibc-rs`/`tower-abci` crates to Tendermint v0.37.0-rc1 compatible commits from `ledger-main` branches of our forks. These updated crates also work with the current Tendermint binaries we are using in CI (i.e. our Tendermint fork - https://github.com/heliaxdev/tendermint/tree/ledger-main).
- points the Docker image and `get_tendermint.sh` script to start using v0.37.0-rc1

NB: after this PR, you could patch in different `tendermint-rs`/`ibc-rs`/`tower-abci` versions like so below (e.g. to try something out, or maybe in an integration branch which uses different versions of these crates)

```toml

[patch."https://github.com/heliaxdev/tendermint-rs"]
tendermint = {git = "https://github.com/heliaxdev/tendermint-rs?branch=ledger-main", rev = "f8f019217130f36eecafac2ad11e35f5bda2ecab"}
tendermint-config = {git = "https://github.com/heliaxdev/tendermint-rs?branch=ledger-main", rev = "f8f019217130f36eecafac2ad11e35f5bda2ecab"}
tendermint-proto = {git = "https://github.com/heliaxdev/tendermint-rs?branch=ledger-main", rev = "f8f019217130f36eecafac2ad11e35f5bda2ecab"}
tendermint-rpc = {git = "https://github.com/heliaxdev/tendermint-rs?branch=ledger-main", rev = "f8f019217130f36eecafac2ad11e35f5bda2ecab"}
tendermint-testgen = {git = "https://github.com/heliaxdev/tendermint-rs?branch=ledger-main", rev = "f8f019217130f36eecafac2ad11e35f5bda2ecab"}
tendermint-light-client = {git = "https://github.com/heliaxdev/tendermint-rs?branch=ledger-main", rev = "f8f019217130f36eecafac2ad11e35f5bda2ecab"}
tendermint-light-client-verifier = {git = "https://github.com/heliaxdev/tendermint-rs?branch=ledger-main", rev = "f8f019217130f36eecafac2ad11e35f5bda2ecab"}

[patch."https://github.com/heliaxdev/ibc-rs"]
ibc = {git = "https://github.com/heliaxdev/ibc-rs?branch=ledger-main", rev = "f7e59c81298c1e44dfabe1155a36ac4efdad478c"}
ibc-proto = {git = "https://github.com/heliaxdev/ibc-rs?branch=ledger-main", rev = "f7e59c81298c1e44dfabe1155a36ac4efdad478c"}
ibc-relayer = {git = "https://github.com/heliaxdev/ibc-rs?branch=ledger-main", rev = "f7e59c81298c1e44dfabe1155a36ac4efdad478c"}

[patch."https://github.com/heliaxdev/tower-abci"]
tower-abci = {git = "https://github.com/heliaxdev/tower-abci?branch=ledger-main", rev = "659d799f2a94238cd45725738624b7f51b96287f"}
```

### CODE REVIEW

**Comment by james-chf** [comment]
Although the `make check-abcipp` CI job is failing in this PR, if you merge in https://github.com/anoma/namada/pull/869 (which is already in `main`), then `make check-abcipp` and `make clippy-abcipp` passes. (Ideally the CI would run against a merge of `main` + the PR branch)

**Comment by james-chf** [comment]
pls update wasm

**Comment by james-chf** [comment]
pls update wasm

**Comment by james-chf** [comment]
pls update wasm

**Comment by tzemanovic** [comment]
will go to cometBFT

**Pull request closed without merging**
