### PR TITLE
Bengt/v0.16 test

### PR DESCRIPTION
**Pull request by bengtlofgren**

### CODE REVIEW

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.15-faster-epochs,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.16,3,heliaxdev@1be9883,ON]

**Pull request closed without merging**
