### PR TITLE
update Rust to 1.81 stable and 2024-09-08 nightly

### PR DESCRIPTION
**Pull request by tzemanovic**
## Describe your changes

Related CI update in https://github.com/heliaxdev/namada-ci/pull/3

## Checklist before merging 
- [ ] If this PR has some consensus breaking changes, I added the corresponding `breaking::` labels
    - This will require 2 reviewers to approve the changes

### CODE REVIEW

**Comment by Fraccaman** [comment]
maybe we should use 1.80.1 ? https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html

**Comment by tzemanovic** [comment]
> maybe we should use 1.80.1 ? https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html

ah yeah, I was going by releases.rs but there's some issue with it not showing

**Comment by brentstone** [comment]
what's the status here?

**Comment by tzemanovic** [comment]
> what's the status here?

it needs rebased, we can also go to 1.81 now

**Comment by sug0** [comment]
can we merge this?

**Comment by brentstone** [comment]
@sug0 chatted with Tomas and decided to wait until we are ready wrt other work to cut a release, then will rebase this and merge as last PR before the release. CI is largely failing atm anyway.

**Pull request merged**
