### PR TITLE
draft v0.16

### PR DESCRIPTION
**Pull request by tzemanovic**
WARNING: ☠️ do not merge this branch into your development branches and do not rely on it being stable. ☠️

contains:
- #1217 
- #1218
- #1295 
- #1304 
- #1152 
- #1138
- #1325 
- #1333

### CODE REVIEW

**Comment by tzemanovic** [comment]
pls update wasm

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.15-faster-epochs,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls update wasm

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.15-faster-epochs,3,heliaxdev@1be9883,ON]

**Comment by tzemanovic** [comment]
released as 0.15.2

**Pull request closed without merging**
