### PR TITLE
add ibc tx host fn to workaround M1/2 WASM compilation issue

### PR DESCRIPTION
**Pull request by tzemanovic**
## Describe your changes

As a workaround for #1831, the IBC tx execution is added as a native host fn.

## Indicate on which release or other PRs this topic is based on:
0.22.0

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Comment by Fraccaman** [comment]
should we add this to draft?

**Comment by brentstone** [comment]
> should we add this to draft?

I'm in favor of it. This also was crucial for me to be able to run e2e tests again.

**Comment by sug0** [comment]
is https://github.com/anoma/namada/issues/1872 still relevant after this merges?

**Comment by tzemanovic** [comment]
> is #1872 still relevant after this merges?

I think so, we can switch it back to wasm at some point

**Pull request merged**
