### PR TITLE
Update flume

### LINKED ISSUE #3932: Update `flume`
Update `flume` to `0.11.1` (https://github.com/zesterer/flume/pull/138). This fixes some crashes in the browser, when running SDK code compiled to wasm.

### PR DESCRIPTION
**Pull request by brentstone**
## Describe your changes
Closes #3932

## Checklist before merging 
- [ ] If this PR has some consensus breaking changes, I added the corresponding `breaking::` labels
    - This will require 2 reviewers to approve the changes
- [ ] If this PR requires changes to the docs or specs, a corresponding PR is opened in the `namada-docs` repo
    - Relevant PR if applies: 
- [ ] If this PR affects services such as `namada-indexer` or `namada-masp-indexer`, a corresponding PR is opened in that repo
    - Relevant PR if applies:

### CODE REVIEW

**Review by sug0 — APPROVED** [review]

**Comment by sug0** [comment]
needs to be rebased on the new `main` to increase the integration test timeout :(

**Comment by sug0** [comment]
@mergifyio requeue

**Comment by Fraccaman** [comment]
@mergify queue

**Comment by Fraccaman** [comment]
@mergify rebase

**Comment by Fraccaman** [comment]
@mergify queue

**Pull request merged**
