### PR TITLE
refactor finalize block

### PR DESCRIPTION
**Pull request by tzemanovic**
## Describe your changes

Refactored token, gov and PoS sub-systems integration in finalize block. The token and PoS logic is moved into their respective crates. Gov proposal exec depends on the shell as well as IBC and PoS so this is kept in `crates/apps/src/lib/node/ledger/shell/governance.rs` for now.

## Indicate on which release or other PRs this topic is based on

0.31.5

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Review by grarco — DISMISSED** [review]
Looks good to me, thank you!

**Review by batconjurer — DISMISSED** [review]

**Comment by brentstone** [comment]
Can we also move https://github.com/anoma/namada/blob/fdafaa685f3cc0da98dc84a443a93314feffea7e/crates/apps/src/lib/node/ledger/shell/finalize_block.rs#L647-L653 out of `apply_inflation`? I suspect it may have been incorrectly placed into this function, it can at least go right into `finalize_block::finalize_block` or some other function, but it has nothing to do with inflation.

**Comment by brentstone** [comment]
Would it also be safer to call `governance::finalize_block` before `token::finalize_block` in case we want governance to execute changes before MASP `update_allowed_conversions` is called ever?

**Comment by brentstone** [comment]
Also, perhaps we could move `proof_of_stake::log_block_rewards` to `proof_of_stake::rewards::log_block_rewards` and `proof_of_stake::record_slashes_from_evidence` to `proof_of_stake::slashing::record_slashes_from_evidence`.

**Comment by tzemanovic** [comment]
> Would it also be safer to call `governance::finalize_block` before `token::finalize_block` in case we want governance to execute changes before MASP `update_allowed_conversions` is called ever?

Yeah, good call

**Comment by tzemanovic** [comment]
@yito88 it looks like the ibc events were in the wrong place and they would have only been applied on new epochs

**Review by brentstone — APPROVED** [review]

**Pull request merged**
